version: "3.9"
services:
  linea-besu:
    image: consensys/linea-besu-package:latest
    container_name: linea-besu
    restart: unless-stopped
    ports:
      - "8545:8545"   # HTTP RPC
      - "8546:8546"   # WS RPC
    command: >
      --profile=advanced-mainnet
      --plugin-linea-l1-rpc-endpoint=https://ethereum.blockpi.network/v1/rpc/<BLOCKPI_API_KEY>
      --rpc-http-enabled=true
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins="*"
      --rpc-http-api=ETH,NET,WEB3,LINEA
      --rpc-ws-enabled=true
      --rpc-ws-host=0.0.0.0
      --rpc-ws-port=8546
    volumes:
      - ./linea-data:/var/lib/besu
